version: '3.3'
services:
  app:
    container_name: home_front
    build:
        context: ./
        dockerfile: Dockerfile
    # image: syukurdocker/home_front
    restart: always
    environment:
        - API_HOST=192.168.0.100
        - API_PORT=8000
        - SPOKE_HOST=192.168.0.121
        - SPOKE_PORT=3000
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=syukur123***
        - POSTGRES_HOST=192.168.0.88
        - POSTGRES_PORT=5432
        - POSTGRES_DB=homeapi
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    volumes:
        - ./log:/app/logs
    ports:
        - '5003:5000'
    depends_on:
        - redis

  redis:
    image: redis:7.4.0-alpine
    restart: always
    volumes:
      - ./cache:/data
    environment:
      - REDIS_PASSWORD=syukur123***
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
