version: '3.3'
services:
  app:
    container_name: home_front
    build:
        context: ./
        dockerfile: Dockerfile
#    image: syukurdocker/home_front
    restart: always
    environment:
        - API_ENDPOINT=http://192.168.0.88:5002
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=syukur123***
        - POSTGRES_HOST=192.168.0.88
        - POSTGRES_PORT=5432
        - POSTGRES_DB=homeapi
    ports:
        - '5003:5000'
